//priority: 9999999

var $CuriosApi = Java.loadClass('top.theillusivec4.curios.api.CuriosApi')
var $Boolean = Java.loadClass('java.lang.Boolean')
var $BlockStateProperties = Java.loadClass('net.minecraft.world.level.block.state.properties.BlockStateProperties')
var $LivingEntity = Java.loadClass('net.minecraft.world.entity.LivingEntity')
var $LivingDamageEvent = Java.loadClass('net.minecraftforge.event.entity.living.LivingDamageEvent')
var $LivingUseTotemEvent = Java.loadClass('net.minecraftforge.event.entity.living.LivingUseTotemEvent')
var $PortalSpawnEvent = Java.loadClass('net.minecraftforge.event.level.BlockEvent$PortalSpawnEvent')
var $AnvilUpdateEvent = Java.loadClass('net.minecraftforge.event.AnvilUpdateEvent')
var $PotionBrewEvent = Java.loadClass('net.minecraftforge.event.brewing.PotionBrewEvent')
var $StairsShape = Java.loadClass('net.minecraft.world.level.block.state.properties.StairsShape')
var $SlabType = Java.loadClass('net.minecraft.world.level.block.state.properties.SlabType')
var $Integer = Java.loadClass('java.lang.Integer')
var $WallSide = Java.loadClass('net.minecraft.world.level.block.state.properties.WallSide')
var $VerticalSlabType = Java.loadClass('org.violetmoon.quark.content.building.block.VerticalSlabBlock$VerticalSlabType')
var $QuarkVerticalSlabBlock = Java.loadClass('org.violetmoon.quark.content.building.block.QuarkVerticalSlabBlock')
var $Half = Java.loadClass('net.minecraft.world.level.block.state.properties.Half')
var $DirectionAxis = Java.loadClass('net.minecraft.core.Direction$Axis')
var $WoodPostBlock = Java.loadClass('org.violetmoon.quark.content.building.block.WoodPostBlock')
var $PostSideType = Java.loadClass('org.violetmoon.quark.content.building.block.WoodPostBlock$PostSideType')
var $ForgeCatnipServices = Java.loadClass('net.createmod.catnip.platform.ForgeCatnipServices')