ServerEvents.recipes(event => {

    const { create } = event.recipes

    //构件
    create.sequenced_assembly(
        'kubejs:rock_core_mechanism',
        'kubejs:rock_core_sheet',
        [
            create.deploying(
                'kubejs:incomplete_rock_core_mechanism',
                [
                    'kubejs:incomplete_rock_core_mechanism',
                    'tconstruct:grout'
                ]
            ),
            create.filling(
                'kubejs:incomplete_rock_core_mechanism',
                [
                    'kubejs:rock_core_mechanism',
                    Fluid.of('minecraft:water', 1000)
                ]
            ),
            create.deploying(
                'kubejs:incomplete_rock_core_mechanism',
                [
                    'kubejs:incomplete_rock_core_mechanism',
                    'create:cogwheel'
                ]
            )
        ],
        'kubejs:incomplete_rock_core_mechanism',
        3
    ).id('kubejs:sequenced_assembly_rock_core_mechanism')//岩核构件

    create.sequenced_assembly(
        'kubejs:electronic_mechanism',
        'kubejs:silicon_sheet',
        [
            create.deploying(
                'kubejs:incomplete_electronic_mechanism',
                [
                    'kubejs:incomplete_electronic_mechanism',
                    'create:electron_tube'
                ]
            ),
            create.deploying(
                'kubejs:incomplete_electronic_mechanism',
                [
                    'kubejs:incomplete_electronic_mechanism',
                    'createaddition:copper_wire'
                ]
            ),
            create.deploying(
                'kubejs:incomplete_electronic_mechanism',
                [
                    'kubejs:incomplete_electronic_mechanism',
                    'kubejs:aluminum_sheet'
                ]
            ),
            create.pressing(
                'kubejs:incomplete_electronic_mechanism',
                'kubejs:incomplete_electronic_mechanism'
            )
        ],
        'kubejs:incomplete_electronic_mechanism',
        5
    ).id('kubejs:sequenced_assembly_electronic_mechanism')//电力构件

    create.sequenced_assembly(
        'kubejs:dense_planet_core_mechanism',
        'kubejs:dense_planet_core_sheet',
        [
            create.deploying(
                'kubejs:incomplete_dense_planet_core_mechanism',
                [
                    'kubejs:incomplete_dense_planet_core_mechanism',
                    'ad_astra:etrium_plate'
                ]
            ),
            create.filling(
                'kubejs:incomplete_dense_planet_core_mechanism',
                [
                    'kubejs:incomplete_dense_planet_core_mechanism',
                    Fluid.of('tconstruct:molten_amethyst', 500)
                ]
            ),
            create.deploying(
                'kubejs:incomplete_dense_planet_core_mechanism',
                [
                    'kubejs:incomplete_dense_planet_core_mechanism',
                    'kubejs:aluminum_alloy_sheet'
                ]
            ),
            create.pressing(
                'kubejs:incomplete_dense_planet_core_mechanism',
                'kubejs:incomplete_dense_planet_core_mechanism'
            )
        ],
        'kubejs:incomplete_dense_planet_core_mechanism',
        5
    ).id('kubejs:sequenced_assembly_dense_planet_core_mechanism')//压缩星核构件

    create.sequenced_assembly(
        'kubejs:echo_mechanism',
        'minecraft:echo_shard',
        [
            create.deploying(
                'kubejs:incomplete_echo_mechanism',
                [
                    'kubejs:incomplete_echo_mechanism',
                    'minecraft:amethyst_shard'
                ]
            ),
            create.deploying(
                'kubejs:incomplete_echo_mechanism',
                [
                    'kubejs:incomplete_echo_mechanism',
                    '#quark:shards'
                ]
            ),
            create.pressing(
                'kubejs:incomplete_echo_mechanism',
                'kubejs:incomplete_echo_mechanism'
            )
        ],
        'kubejs:incomplete_echo_mechanism',
        3
    ).id('kubejs:sequenced_assembly_echo_mechanism')//回响构件

    create.sequenced_assembly(
        'kubejs:creative_mechanism',
        'createutilities:void_steel_sheet',
        [
            create.deploying(
                'kubejs:incomplete_creative_mechanism',
                [
                    'kubejs:incomplete_creative_mechanism',
                    'createutilities:graviton_tube'
                ]
            ),
            create.filling(
                'kubejs:incomplete_creative_mechanism',
                [
                    'kubejs:incomplete_creative_mechanism',
                    Fluid.of('kubejs:molten_shadow_steel', 1000)
                ]
            ),
            create.deploying(
                'kubejs:incomplete_creative_mechanism',
                [
                    'kubejs:incomplete_creative_mechanism',
                    'kubejs:dense_planet_core_mechanism'
                ]
            ),
            create.pressing(
                'kubejs:incomplete_creative_mechanism',
                'kubejs:incomplete_creative_mechanism'
            ),
            create.filling(
                'kubejs:incomplete_creative_mechanism',
                [
                    'kubejs:incomplete_creative_mechanism',
                    Fluid.of('kubejs:molten_refined_radiance', 1000)
                ]
            )
        ],
        'kubejs:incomplete_creative_mechanism',
        7
    ).id('kubejs:sequenced_assembly_creative_mechanism')//创造构件

    create.sequenced_assembly(
        'kubejs:aviation_mechanism',
        'ad_astra:steel_plate',
        [
            create.deploying(
                'kubejs:incomplete_aviation_mechanism',
                [
                    'kubejs:incomplete_aviation_mechanism',
                    'createaddition:diamond_grit'
                ]
            ),
            create.filling(
                'kubejs:incomplete_aviation_mechanism',
                [
                    'kubejs:incomplete_aviation_mechanism',
                    Fluid.of('tconstruct:molten_obsidian', 1000)
                ]
            ),
            create.pressing(
                'kubejs:incomplete_aviation_mechanism',
                'kubejs:incomplete_aviation_mechanism'
            )
        ],
        'kubejs:incomplete_aviation_mechanism',
        5
    ).id('kubejs:sequenced_assembly_aviation_mechanism')//航空构件

    create.sequenced_assembly(
        'kubejs:void_mechanism',
        'createutilities:void_steel_sheet',
        [
            create.deploying(
                'kubejs:incomplete_void_mechanism',
                [
                    'kubejs:incomplete_void_mechanism',
                    'createnuclear:reinforced_glass'
                ]
            ),
            create.filling(
                'kubejs:incomplete_void_mechanism',
                [
                    'kubejs:incomplete_void_mechanism',
                    Fluid.of('tconstruct:molten_ender', 1000)
                ]
            ),
            create.pressing(
                'kubejs:incomplete_void_mechanism',
                'kubejs:incomplete_void_mechanism'
            ),
            create.deploying(
                'kubejs:incomplete_void_mechanism',
                [
                    'kubejs:incomplete_void_mechanism',
                    'kubejs:dense_planet_core_sheet'
                ]
            )
        ],
        'kubejs:incomplete_void_mechanism',
        5
    ).id('kubejs:sequenced_assembly_void_mechanism')//虚空构件

    create.sequenced_assembly(
        'kubejs:nuclear_mechanism',
        'kubejs:lead_sheet',
        [
            create.deploying(
                'kubejs:incomplete_nuclear_mechanism',
                [
                    'kubejs:incomplete_nuclear_mechanism',
                    'kubejs:silicon_sheet'
                ]
            ),
            create.deploying(
                'kubejs:incomplete_nuclear_mechanism',
                [
                    'kubejs:incomplete_nuclear_mechanism',
                    'createnuclear:uranium_powder'
                ]
            ),
            create.filling(
                'kubejs:incomplete_nuclear_mechanism',
                [
                    'kubejs:incomplete_nuclear_mechanism',
                    Fluid.of('ad_astra:cryo_fuel', 500)
                ]
            ),
            create.pressing(
                'kubejs:incomplete_nuclear_mechanism',
                'kubejs:incomplete_nuclear_mechanism'
            )
        ],
        'kubejs:incomplete_nuclear_mechanism',
        5
    ).id('kubejs:sequenced_assembly_nuclear_mechanism')//核能构件
})