//priority: 9999999

var $CuriosApi = Java.loadClass('top.theillusivec4.curios.api.CuriosApi')
var $AllGuiTextures = Java.loadClass('com.simibubi.create.foundation.gui.AllGuiTextures')
var $AnimatedKinetics = Java.loadClass('com.simibubi.create.compat.jei.category.animations.AnimatedKinetics')
var $AllPartialModels = Java.loadClass('com.simibubi.create.AllPartialModels')
var $CreateRecipeCategory = Java.loadClass('com.simibubi.create.compat.jei.category.CreateRecipeCategory')
var $Axis = Java.loadClass('com.mojang.math.Axis')
var $DoubleItemIcon = Java.loadClass('com.simibubi.create.compat.jei.DoubleItemIcon')
var $RecipeIngredientRole = Java.loadClass('mezz.jei.api.recipe.RecipeIngredientRole')
var $Integer = Java.loadClass('java.lang.Integer')
var $DeployerBlock = Java.loadClass('com.simibubi.create.content.kinetics.deployer.DeployerBlock')
var $AnimationTickHolder = Java.loadClass('net.createmod.catnip.animation.AnimationTickHolder')
var $DirectionAxis = Java.loadClass('net.minecraft.core.Direction$Axis')
var $Boolean = Java.loadClass('java.lang.Boolean')
var $StairsShape = Java.loadClass('net.minecraft.world.level.block.state.properties.StairsShape')
var $SlabType = Java.loadClass('net.minecraft.world.level.block.state.properties.SlabType')
var $AttachFace = Java.loadClass('net.minecraft.world.level.block.state.properties.AttachFace')
var $MultiBufferSource = Java.loadClass('net.minecraft.client.renderer.MultiBufferSource')
var $Tesselator = Java.loadClass('com.mojang.blaze3d.vertex.Tesselator')
var $UIRenderHelper = Java.loadClass('net.createmod.catnip.gui.UIRenderHelper')
var $ForgeCatnipServices = Java.loadClass('net.createmod.catnip.platform.ForgeCatnipServices')
var $LightTexture = Java.loadClass('net.minecraft.client.renderer.LightTexture')
var $Lighting = Java.loadClass('com.mojang.blaze3d.platform.Lighting')